version: '3'
services:
  api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - adminer
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  

